version: '3'
services:
  kasm_agent:
    container_name: kasm_agent
    user: root
    image: "kasmweb/agent:1.16.1"
    read_only: true
    networks:
      - kasm_default_network
    volumes:
      - /data/kasm/1.16.1:/data/kasm/current
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/kasm/1.16.1/conf/nginx:/etc/nginx/conf.d
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
  proxy:
    container_name: kasm_proxy
    image: "kasmweb/proxy:1.16.1"
    ports:
      - "443:443"
    networks:
      - kasm_default_network
      - kasm_sidecar_network
    volumes:
      - /data/kasm/1.16.1/conf/nginx:/etc/nginx/conf.d:ro
      - /data/kasm/1.16.1/certs/kasm_nginx.key:/etc/ssl/private/kasm_nginx.key
      - /data/kasm/1.16.1/certs/kasm_nginx.crt:/etc/ssl/certs/kasm_nginx.crt
      - /data/kasm/1.16.1/log/nginx:/var/log/external/nginx/
      - /data/kasm/1.16.1/log/logrotate:/var/log/external/logrotate/
    restart: always
    depends_on:
      - kasm_agent
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
networks:
  kasm_default_network:
    external: true
  kasm_sidecar_network:
    external: true
